---
language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
dist: trusty
sudo: false
group: beta
cache:
  - pip
  - directories:
      - $HOME/.pre-commit

install:
  - pip install pre-commit docutils

script:
  - pre-commit run --all-files
  - python setup.py check -mrs
  - pip install ./

notifications:
  email: false
